### ISSUE TITLE
Questies Bug trigger (H) side

### ISSUE THREAD

**Issue by Tarkusx** [Aldori15/Questie-335-AshenOrder#1]
When we click on TASKBOARD on Horde side at level 60 , here a screenshot . Look like theres a DB missing update .
![Screenshot 2024-11-13 091127](https://github.com/user-attachments/assets/b4e0acc0-f587-4a57-9628-42b1e8e169a4)

**Comment by Aldori15** [comment]
@Tarkusx Thanks for the report.  I'm able to replicate on my end.  Working on the fix now.

**Comment by Aldori15** [comment]
@Tarkusx This has been resolved with the latest commit.  Please grab the latest downloads.
