### ISSUE TITLE
[ QUEST BUG ] - Quest Name Seal of Ascension LBRS

### ISSUE THREAD

**Issue by Tarkusx** [Aldori15/Questie-335-AshenOrder#2]
**Quest Name**
Seal of Ascension

**Quest Location/Zone**
LBRS.

**Screenshot(s)**
If applicable, please add a screenshot that shows the error.

**Additional context/notes**
Accepting / Completing Quest
![WoWScrnShot_112224_153648](https://github.com/user-attachments/assets/d8bba7fa-baaa-4c66-8ee9-99000c2ef032)
![WoWScrnShot_112224_153655](https://github.com/user-attachments/assets/5b8f13a9-ce15-4985-a207-6d450d6a8a12)

**Comment by Aldori15** [comment]
@Tarkusx Are you playing on the Ashen Order repack?

**Comment by Aldori15** [comment]
@Tarkusx This has been resolved with the newest update.  Closing out this bug.

Let me know if you have any other issues with this one.
